#!/usr/bin/env bash

get_record() {
    subdomain="$1"
    domain="$2"

    result=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; print $4, $5}')
    record_type=$(echo "$result" | awk '{print $1}')
    destination=$(echo "$result" | awk '{print $2}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ "$#" -eq 1 ]; then
    domain="$1"

    get_record "www" "$domain"
    get_record "lb-01" "$domain"
    get_record "web-01" "$domain"
    get_record "web-02" "$domain"
elif [ "$#" -eq 2 ]; then
    domain="$1"
    subdomain="$2"

    get_record "$subdomain" "$domain"
fi
